version: 2
mergeable:
  - when: 'pull_request.*, pull_request_review.*'
    name: Approvals check
    filter:
      - do: payload
        pull_request:
          title:
            must_exclude:
              regex: ^Feedback$
              regex_flag: none
    validate:
      - do: description
        no_empty:
              enabled: true
              message: "Description should not be empty."
      - do: approvals
        min:
          count: 0